services:
  backend:
    build: ./back
    container_name: api
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: front
    ports:
      - "8444:80"
    depends_on:
      - backend
    restart: unless-stopped